targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          generatedFileHeader: "// ignore_for_file: type=lint\n"
          scalars:
            HexColorCode:
              type: String
            YearMonth:
              type: String
